package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Assignmentlogs generated by hbm2java
 */
public class Assignmentlogs  implements java.io.Serializable {


     private Long MTxId;
     private long MCompanyId;
     private long MFromId;
     private long MToId;
     private long MCheckId;
     private Date MTimestamp;
     private Byte MAction;
     private String MComments;

    public Assignmentlogs() {
    }

	
    public Assignmentlogs(long MCompanyId, long MFromId, long MToId, long MCheckId) {
        this.MCompanyId = MCompanyId;
        this.MFromId = MFromId;
        this.MToId = MToId;
        this.MCheckId = MCheckId;
    }
    public Assignmentlogs(long MCompanyId, long MFromId, long MToId, long MCheckId, Date MTimestamp, Byte MAction, String MComments) {
       this.MCompanyId = MCompanyId;
       this.MFromId = MFromId;
       this.MToId = MToId;
       this.MCheckId = MCheckId;
       this.MTimestamp = MTimestamp;
       this.MAction = MAction;
       this.MComments = MComments;
    }
   
    public Long getMTxId() {
        return this.MTxId;
    }
    
    public void setMTxId(Long MTxId) {
        this.MTxId = MTxId;
    }
    public long getMCompanyId() {
        return this.MCompanyId;
    }
    
    public void setMCompanyId(long MCompanyId) {
        this.MCompanyId = MCompanyId;
    }
    public long getMFromId() {
        return this.MFromId;
    }
    
    public void setMFromId(long MFromId) {
        this.MFromId = MFromId;
    }
    public long getMToId() {
        return this.MToId;
    }
    
    public void setMToId(long MToId) {
        this.MToId = MToId;
    }
    public long getMCheckId() {
        return this.MCheckId;
    }
    
    public void setMCheckId(long MCheckId) {
        this.MCheckId = MCheckId;
    }
    public Date getMTimestamp() {
        return this.MTimestamp;
    }
    
    public void setMTimestamp(Date MTimestamp) {
        this.MTimestamp = MTimestamp;
    }
    public Byte getMAction() {
        return this.MAction;
    }
    
    public void setMAction(Byte MAction) {
        this.MAction = MAction;
    }
    public String getMComments() {
        return this.MComments;
    }
    
    public void setMComments(String MComments) {
        this.MComments = MComments;
    }




}


