package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Checklists generated by hbm2java
 */
public class Checklists  implements java.io.Serializable {


     private Long MCheckId;
     private long MTemplateId;
     private Byte MImportance;
     private Byte MStatus;
     private Byte MIsForward;
     private Byte MSeverity;
     private Date MStartTimestamp;
     private Date MEndTimestamp;
     private Byte MIsTimeBound;
     private Byte MIsEventBased;
     private Byte MDaysInWeek;

    public Checklists() {
    }

	
    public Checklists(long MTemplateId) {
        this.MTemplateId = MTemplateId;
    }
    public Checklists(long MTemplateId, Byte MImportance, Byte MStatus, Byte MIsForward, Byte MSeverity, Date MStartTimestamp, Date MEndTimestamp, Byte MIsTimeBound, Byte MIsEventBased, Byte MDaysInWeek) {
       this.MTemplateId = MTemplateId;
       this.MImportance = MImportance;
       this.MStatus = MStatus;
       this.MIsForward = MIsForward;
       this.MSeverity = MSeverity;
       this.MStartTimestamp = MStartTimestamp;
       this.MEndTimestamp = MEndTimestamp;
       this.MIsTimeBound = MIsTimeBound;
       this.MIsEventBased = MIsEventBased;
       this.MDaysInWeek = MDaysInWeek;
    }
   
    public Long getMCheckId() {
        return this.MCheckId;
    }
    
    public void setMCheckId(Long MCheckId) {
        this.MCheckId = MCheckId;
    }
    public long getMTemplateId() {
        return this.MTemplateId;
    }
    
    public void setMTemplateId(long MTemplateId) {
        this.MTemplateId = MTemplateId;
    }
    public Byte getMImportance() {
        return this.MImportance;
    }
    
    public void setMImportance(Byte MImportance) {
        this.MImportance = MImportance;
    }
    public Byte getMStatus() {
        return this.MStatus;
    }
    
    public void setMStatus(Byte MStatus) {
        this.MStatus = MStatus;
    }
    public Byte getMIsForward() {
        return this.MIsForward;
    }
    
    public void setMIsForward(Byte MIsForward) {
        this.MIsForward = MIsForward;
    }
    public Byte getMSeverity() {
        return this.MSeverity;
    }
    
    public void setMSeverity(Byte MSeverity) {
        this.MSeverity = MSeverity;
    }
    public Date getMStartTimestamp() {
        return this.MStartTimestamp;
    }
    
    public void setMStartTimestamp(Date MStartTimestamp) {
        this.MStartTimestamp = MStartTimestamp;
    }
    public Date getMEndTimestamp() {
        return this.MEndTimestamp;
    }
    
    public void setMEndTimestamp(Date MEndTimestamp) {
        this.MEndTimestamp = MEndTimestamp;
    }
    public Byte getMIsTimeBound() {
        return this.MIsTimeBound;
    }
    
    public void setMIsTimeBound(Byte MIsTimeBound) {
        this.MIsTimeBound = MIsTimeBound;
    }
    public Byte getMIsEventBased() {
        return this.MIsEventBased;
    }
    
    public void setMIsEventBased(Byte MIsEventBased) {
        this.MIsEventBased = MIsEventBased;
    }
    public Byte getMDaysInWeek() {
        return this.MDaysInWeek;
    }
    
    public void setMDaysInWeek(Byte MDaysInWeek) {
        this.MDaysInWeek = MDaysInWeek;
    }




}


