package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA



/**
 * Checklisttemplate generated by hbm2java
 */
public class Checklisttemplate  implements java.io.Serializable {


     private Long MTemplateId;
     private long MCompanyId;
     private String MCheckList;
     private String MDescription;
     private Byte MType;
     private long MCategoryId;

    public Checklisttemplate() {
    }

	
    public Checklisttemplate(long MCompanyId, long MCategoryId) {
        this.MCompanyId = MCompanyId;
        this.MCategoryId = MCategoryId;
    }
    public Checklisttemplate(long MCompanyId, String MCheckList, String MDescription, Byte MType, long MCategoryId) {
       this.MCompanyId = MCompanyId;
       this.MCheckList = MCheckList;
       this.MDescription = MDescription;
       this.MType = MType;
       this.MCategoryId = MCategoryId;
    }
   
    public Long getMTemplateId() {
        return this.MTemplateId;
    }
    
    public void setMTemplateId(Long MTemplateId) {
        this.MTemplateId = MTemplateId;
    }
    public long getMCompanyId() {
        return this.MCompanyId;
    }
    
    public void setMCompanyId(long MCompanyId) {
        this.MCompanyId = MCompanyId;
    }
    public String getMCheckList() {
        return this.MCheckList;
    }
    
    public void setMCheckList(String MCheckList) {
        this.MCheckList = MCheckList;
    }
    public String getMDescription() {
        return this.MDescription;
    }
    
    public void setMDescription(String MDescription) {
        this.MDescription = MDescription;
    }
    public Byte getMType() {
        return this.MType;
    }
    
    public void setMType(Byte MType) {
        this.MType = MType;
    }
    public long getMCategoryId() {
        return this.MCategoryId;
    }
    
    public void setMCategoryId(long MCategoryId) {
        this.MCategoryId = MCategoryId;
    }




}


