package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA



/**
 * Clientinfo generated by hbm2java
 */
public class Clientinfo  implements java.io.Serializable {


     private Long MClientId;
     private String MClientName;
     private long MCompanyId;

    public Clientinfo() {
    }

	
    public Clientinfo(long MCompanyId) {
        this.MCompanyId = MCompanyId;
    }
    public Clientinfo(String MClientName, long MCompanyId) {
       this.MClientName = MClientName;
       this.MCompanyId = MCompanyId;
    }
   
    public Long getMClientId() {
        return this.MClientId;
    }
    
    public void setMClientId(Long MClientId) {
        this.MClientId = MClientId;
    }
    public String getMClientName() {
        return this.MClientName;
    }
    
    public void setMClientName(String MClientName) {
        this.MClientName = MClientName;
    }
    public long getMCompanyId() {
        return this.MCompanyId;
    }
    
    public void setMCompanyId(long MCompanyId) {
        this.MCompanyId = MCompanyId;
    }




}


