package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Companyevents generated by hbm2java
 */
public class Companyevents  implements java.io.Serializable {


     private long MEventId;
     private String MEventName;
     private long MDeptId;
     private Date MStartTime;
     private Date MEndTime;
     private Byte MStatus;
     private Long MCompanyId;

    public Companyevents() {
    }

	
    public Companyevents(long MEventId, long MDeptId) {
        this.MEventId = MEventId;
        this.MDeptId = MDeptId;
    }
    public Companyevents(long MEventId, String MEventName, long MDeptId, Date MStartTime, Date MEndTime, Byte MStatus, Long MCompanyId) {
       this.MEventId = MEventId;
       this.MEventName = MEventName;
       this.MDeptId = MDeptId;
       this.MStartTime = MStartTime;
       this.MEndTime = MEndTime;
       this.MStatus = MStatus;
       this.MCompanyId = MCompanyId;
    }
   
    public long getMEventId() {
        return this.MEventId;
    }
    
    public void setMEventId(long MEventId) {
        this.MEventId = MEventId;
    }
    public String getMEventName() {
        return this.MEventName;
    }
    
    public void setMEventName(String MEventName) {
        this.MEventName = MEventName;
    }
    public long getMDeptId() {
        return this.MDeptId;
    }
    
    public void setMDeptId(long MDeptId) {
        this.MDeptId = MDeptId;
    }
    public Date getMStartTime() {
        return this.MStartTime;
    }
    
    public void setMStartTime(Date MStartTime) {
        this.MStartTime = MStartTime;
    }
    public Date getMEndTime() {
        return this.MEndTime;
    }
    
    public void setMEndTime(Date MEndTime) {
        this.MEndTime = MEndTime;
    }
    public Byte getMStatus() {
        return this.MStatus;
    }
    
    public void setMStatus(Byte MStatus) {
        this.MStatus = MStatus;
    }
    public Long getMCompanyId() {
        return this.MCompanyId;
    }
    
    public void setMCompanyId(Long MCompanyId) {
        this.MCompanyId = MCompanyId;
    }




}


