package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA



/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Long MDeptId;
     private String MDeptName;
     private Long MCompanyId;

    public Department() {
    }

    public Department(String MDeptName, Long MCompanyId) {
       this.MDeptName = MDeptName;
       this.MCompanyId = MCompanyId;
    }
   
    public Long getMDeptId() {
        return this.MDeptId;
    }
    
    public void setMDeptId(Long MDeptId) {
        this.MDeptId = MDeptId;
    }
    public String getMDeptName() {
        return this.MDeptName;
    }
    
    public void setMDeptName(String MDeptName) {
        this.MDeptName = MDeptName;
    }
    public Long getMCompanyId() {
        return this.MCompanyId;
    }
    
    public void setMCompanyId(Long MCompanyId) {
        this.MCompanyId = MCompanyId;
    }




}


