package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Long MEmpId;
     private String MEmpName;
     private long MCompanyId;
     private long MDesignationId;
     private long MDepartmentId;
     private long MManagerId;
     private String MEmailId;
     private Long MAuthority;

    public Employee() {
    }

	
    public Employee(String MEmpName, long MCompanyId, long MDesignationId, long MDepartmentId, long MManagerId, String MEmailId) {
        this.MEmpName = MEmpName;
        this.MCompanyId = MCompanyId;
        this.MDesignationId = MDesignationId;
        this.MDepartmentId = MDepartmentId;
        this.MManagerId = MManagerId;
        this.MEmailId = MEmailId;
    }
    public Employee(String MEmpName, long MCompanyId, long MDesignationId, long MDepartmentId, long MManagerId, String MEmailId, Long MAuthority) {
       this.MEmpName = MEmpName;
       this.MCompanyId = MCompanyId;
       this.MDesignationId = MDesignationId;
       this.MDepartmentId = MDepartmentId;
       this.MManagerId = MManagerId;
       this.MEmailId = MEmailId;
       this.MAuthority = MAuthority;
    }
   
    public Long getMEmpId() {
        return this.MEmpId;
    }
    
    public void setMEmpId(Long MEmpId) {
        this.MEmpId = MEmpId;
    }
    public String getMEmpName() {
        return this.MEmpName;
    }
    
    public void setMEmpName(String MEmpName) {
        this.MEmpName = MEmpName;
    }
    public long getMCompanyId() {
        return this.MCompanyId;
    }
    
    public void setMCompanyId(long MCompanyId) {
        this.MCompanyId = MCompanyId;
    }
    public long getMDesignationId() {
        return this.MDesignationId;
    }
    
    public void setMDesignationId(long MDesignationId) {
        this.MDesignationId = MDesignationId;
    }
    public long getMDepartmentId() {
        return this.MDepartmentId;
    }
    
    public void setMDepartmentId(long MDepartmentId) {
        this.MDepartmentId = MDepartmentId;
    }
    public long getMManagerId() {
        return this.MManagerId;
    }
    
    public void setMManagerId(long MManagerId) {
        this.MManagerId = MManagerId;
    }
    public String getMEmailId() {
        return this.MEmailId;
    }
    
    public void setMEmailId(String MEmailId) {
        this.MEmailId = MEmailId;
    }
    public Long getMAuthority() {
        return this.MAuthority;
    }
    
    public void setMAuthority(Long MAuthority) {
        this.MAuthority = MAuthority;
    }




}


