package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA



/**
 * Logininfo generated by hbm2java
 */
public class Logininfo  implements java.io.Serializable {


     private String MEmailId;
     private String MPassword;

    public Logininfo() {
    }

	
    public Logininfo(String MEmailId) {
        this.MEmailId = MEmailId;
    }
    public Logininfo(String MEmailId, String MPassword) {
       this.MEmailId = MEmailId;
       this.MPassword = MPassword;
    }
   
    public String getMEmailId() {
        return this.MEmailId;
    }
    
    public void setMEmailId(String MEmailId) {
        this.MEmailId = MEmailId;
    }
    public String getMPassword() {
        return this.MPassword;
    }
    
    public void setMPassword(String MPassword) {
        this.MPassword = MPassword;
    }




}


