package com.executionist;
// Generated Feb 6, 2013 10:35:25 AM by Hibernate Tools 3.2.1.GA



/**
 * Projectinfo generated by hbm2java
 */
public class Projectinfo  implements java.io.Serializable {


     private Long MProjectId;
     private String MProjectName;
     private long MClientId;

    public Projectinfo() {
    }

	
    public Projectinfo(long MClientId) {
        this.MClientId = MClientId;
    }
    public Projectinfo(String MProjectName, long MClientId) {
       this.MProjectName = MProjectName;
       this.MClientId = MClientId;
    }
   
    public Long getMProjectId() {
        return this.MProjectId;
    }
    
    public void setMProjectId(Long MProjectId) {
        this.MProjectId = MProjectId;
    }
    public String getMProjectName() {
        return this.MProjectName;
    }
    
    public void setMProjectName(String MProjectName) {
        this.MProjectName = MProjectName;
    }
    public long getMClientId() {
        return this.MClientId;
    }
    
    public void setMClientId(long MClientId) {
        this.MClientId = MClientId;
    }




}


